typography_spectrum: 0.5804546028375626
color:
  saturation: 0.5314132666680962
  brandStrength: 0.5673029706813395
  rhythmicContrast: 0.3045178120955825
  brandColors:
    - '#63A69F'
    - '#F2E1AC'
    - '#F2836B'
    - '#F2594B'
    - '#CD2C24'
  lightness: 0.42110581416636705
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5667451373301446
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Jan Hosa
  email: jan.hosa@prosiebensat1puls4.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cbadf1ab-525b-4f7c-b74b-dd81b67affff.png
name: 4CREATIVE Solutions
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Guten Tag!
description: 'Schön, Dich wieder zu sehen.'
purpose: []
