typography_spectrum: 0.24682
color:
  saturation: 0.2344598053023219
  brandStrength: 0.9137738591525704
  rhythmicContrast: 0.25
  brandColors:
    - '#000000'
    - '#e5006e'
    - '#ab0052'
    - '#e83626'
    - '#ff0000'
  lightness: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1971326
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Jan Hosa
  email: jan.hosa@prosiebensat1puls4.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cbadf1ab-525b-4f7c-b74b-dd81b67affff.png
name: 4CREATIVE Solutions
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Guten Tag!
description: 'Schön, Dich wieder zu sehen.'
purpose: []
